// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zodiatic/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateLunar struct {
	Creator      string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Yyyymmdd     uint64   `protobuf:"varint,2,opt,name=yyyymmdd,proto3" json:"yyyymmdd,omitempty"`
	Date         string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	LunarNumber  []uint64 `protobuf:"varint,4,rep,packed,name=lunarNumber,proto3" json:"lunarNumber,omitempty"`
	Lunar        string   `protobuf:"bytes,5,opt,name=lunar,proto3" json:"lunar,omitempty"`
	EightWords   string   `protobuf:"bytes,6,opt,name=eightWords,proto3" json:"eightWords,omitempty"`
	GodDirection string   `protobuf:"bytes,7,opt,name=godDirection,proto3" json:"godDirection,omitempty"`
	GoodFor      string   `protobuf:"bytes,8,opt,name=goodFor,proto3" json:"goodFor,omitempty"`
	BadFor       string   `protobuf:"bytes,9,opt,name=badFor,proto3" json:"badFor,omitempty"`
}

func (m *MsgCreateLunar) Reset()         { *m = MsgCreateLunar{} }
func (m *MsgCreateLunar) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLunar) ProtoMessage()    {}
func (*MsgCreateLunar) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{0}
}
func (m *MsgCreateLunar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLunar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLunar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLunar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLunar.Merge(m, src)
}
func (m *MsgCreateLunar) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLunar) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLunar.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLunar proto.InternalMessageInfo

func (m *MsgCreateLunar) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateLunar) GetYyyymmdd() uint64 {
	if m != nil {
		return m.Yyyymmdd
	}
	return 0
}

func (m *MsgCreateLunar) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MsgCreateLunar) GetLunarNumber() []uint64 {
	if m != nil {
		return m.LunarNumber
	}
	return nil
}

func (m *MsgCreateLunar) GetLunar() string {
	if m != nil {
		return m.Lunar
	}
	return ""
}

func (m *MsgCreateLunar) GetEightWords() string {
	if m != nil {
		return m.EightWords
	}
	return ""
}

func (m *MsgCreateLunar) GetGodDirection() string {
	if m != nil {
		return m.GodDirection
	}
	return ""
}

func (m *MsgCreateLunar) GetGoodFor() string {
	if m != nil {
		return m.GoodFor
	}
	return ""
}

func (m *MsgCreateLunar) GetBadFor() string {
	if m != nil {
		return m.BadFor
	}
	return ""
}

type MsgCreateLunarResponse struct {
}

func (m *MsgCreateLunarResponse) Reset()         { *m = MsgCreateLunarResponse{} }
func (m *MsgCreateLunarResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLunarResponse) ProtoMessage()    {}
func (*MsgCreateLunarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{1}
}
func (m *MsgCreateLunarResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLunarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLunarResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLunarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLunarResponse.Merge(m, src)
}
func (m *MsgCreateLunarResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLunarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLunarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLunarResponse proto.InternalMessageInfo

type MsgUpdateLunar struct {
	Creator      string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Yyyymmdd     uint64   `protobuf:"varint,2,opt,name=yyyymmdd,proto3" json:"yyyymmdd,omitempty"`
	Date         string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	LunarNumber  []uint64 `protobuf:"varint,4,rep,packed,name=lunarNumber,proto3" json:"lunarNumber,omitempty"`
	Lunar        string   `protobuf:"bytes,5,opt,name=lunar,proto3" json:"lunar,omitempty"`
	EightWords   string   `protobuf:"bytes,6,opt,name=eightWords,proto3" json:"eightWords,omitempty"`
	GodDirection string   `protobuf:"bytes,7,opt,name=godDirection,proto3" json:"godDirection,omitempty"`
	GoodFor      string   `protobuf:"bytes,8,opt,name=goodFor,proto3" json:"goodFor,omitempty"`
	BadFor       string   `protobuf:"bytes,9,opt,name=badFor,proto3" json:"badFor,omitempty"`
}

func (m *MsgUpdateLunar) Reset()         { *m = MsgUpdateLunar{} }
func (m *MsgUpdateLunar) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLunar) ProtoMessage()    {}
func (*MsgUpdateLunar) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{2}
}
func (m *MsgUpdateLunar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLunar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLunar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLunar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLunar.Merge(m, src)
}
func (m *MsgUpdateLunar) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLunar) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLunar.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLunar proto.InternalMessageInfo

func (m *MsgUpdateLunar) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateLunar) GetYyyymmdd() uint64 {
	if m != nil {
		return m.Yyyymmdd
	}
	return 0
}

func (m *MsgUpdateLunar) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MsgUpdateLunar) GetLunarNumber() []uint64 {
	if m != nil {
		return m.LunarNumber
	}
	return nil
}

func (m *MsgUpdateLunar) GetLunar() string {
	if m != nil {
		return m.Lunar
	}
	return ""
}

func (m *MsgUpdateLunar) GetEightWords() string {
	if m != nil {
		return m.EightWords
	}
	return ""
}

func (m *MsgUpdateLunar) GetGodDirection() string {
	if m != nil {
		return m.GodDirection
	}
	return ""
}

func (m *MsgUpdateLunar) GetGoodFor() string {
	if m != nil {
		return m.GoodFor
	}
	return ""
}

func (m *MsgUpdateLunar) GetBadFor() string {
	if m != nil {
		return m.BadFor
	}
	return ""
}

type MsgUpdateLunarResponse struct {
}

func (m *MsgUpdateLunarResponse) Reset()         { *m = MsgUpdateLunarResponse{} }
func (m *MsgUpdateLunarResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLunarResponse) ProtoMessage()    {}
func (*MsgUpdateLunarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{3}
}
func (m *MsgUpdateLunarResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLunarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLunarResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLunarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLunarResponse.Merge(m, src)
}
func (m *MsgUpdateLunarResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLunarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLunarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLunarResponse proto.InternalMessageInfo

type MsgDeleteLunar struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Yyyymmdd uint64 `protobuf:"varint,2,opt,name=yyyymmdd,proto3" json:"yyyymmdd,omitempty"`
}

func (m *MsgDeleteLunar) Reset()         { *m = MsgDeleteLunar{} }
func (m *MsgDeleteLunar) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLunar) ProtoMessage()    {}
func (*MsgDeleteLunar) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{4}
}
func (m *MsgDeleteLunar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLunar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLunar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLunar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLunar.Merge(m, src)
}
func (m *MsgDeleteLunar) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLunar) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLunar.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLunar proto.InternalMessageInfo

func (m *MsgDeleteLunar) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteLunar) GetYyyymmdd() uint64 {
	if m != nil {
		return m.Yyyymmdd
	}
	return 0
}

type MsgDeleteLunarResponse struct {
}

func (m *MsgDeleteLunarResponse) Reset()         { *m = MsgDeleteLunarResponse{} }
func (m *MsgDeleteLunarResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLunarResponse) ProtoMessage()    {}
func (*MsgDeleteLunarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8e5eacab879484, []int{5}
}
func (m *MsgDeleteLunarResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLunarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLunarResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLunarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLunarResponse.Merge(m, src)
}
func (m *MsgDeleteLunarResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLunarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLunarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLunarResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateLunar)(nil), "zodiatic.zodiatic.zodiatic.MsgCreateLunar")
	proto.RegisterType((*MsgCreateLunarResponse)(nil), "zodiatic.zodiatic.zodiatic.MsgCreateLunarResponse")
	proto.RegisterType((*MsgUpdateLunar)(nil), "zodiatic.zodiatic.zodiatic.MsgUpdateLunar")
	proto.RegisterType((*MsgUpdateLunarResponse)(nil), "zodiatic.zodiatic.zodiatic.MsgUpdateLunarResponse")
	proto.RegisterType((*MsgDeleteLunar)(nil), "zodiatic.zodiatic.zodiatic.MsgDeleteLunar")
	proto.RegisterType((*MsgDeleteLunarResponse)(nil), "zodiatic.zodiatic.zodiatic.MsgDeleteLunarResponse")
}

func init() { proto.RegisterFile("zodiatic/tx.proto", fileDescriptor_0a8e5eacab879484) }

var fileDescriptor_0a8e5eacab879484 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x36, 0xfd, 0x37, 0x15, 0xc1, 0xa5, 0x94, 0x25, 0x87, 0x10, 0x7a, 0x2a, 0x82,
	0x29, 0xd4, 0x37, 0xd0, 0x52, 0x2f, 0xd6, 0x43, 0x40, 0x04, 0x6f, 0x49, 0x76, 0x49, 0x03, 0x4d,
	0x37, 0x6c, 0xb6, 0xd0, 0xf8, 0x04, 0x1e, 0x7d, 0x2c, 0x8f, 0xc5, 0x93, 0x47, 0x69, 0x5f, 0x44,
	0xb2, 0x6d, 0xe2, 0x16, 0x2b, 0x11, 0xbc, 0x7a, 0x9b, 0x6f, 0xe6, 0x9b, 0x7c, 0xe4, 0xb7, 0xcb,
	0xc2, 0xd9, 0x13, 0x23, 0xa1, 0x2b, 0x42, 0x7f, 0x28, 0x56, 0x76, 0xcc, 0x99, 0x60, 0xc8, 0xc8,
	0x5b, 0xf6, 0xb7, 0xc2, 0xe8, 0x16, 0xf6, 0xf9, 0x72, 0xe1, 0xf2, 0xdd, 0x46, 0xff, 0xb9, 0x0a,
	0xa7, 0xd3, 0x24, 0xb8, 0xe6, 0xd4, 0x15, 0xf4, 0x36, 0x1b, 0x20, 0x0c, 0x4d, 0x3f, 0x93, 0x8c,
	0x63, 0xcd, 0xd2, 0x06, 0x6d, 0x27, 0x97, 0xc8, 0x80, 0x56, 0x9a, 0xa6, 0x69, 0x14, 0x11, 0x82,
	0xab, 0x96, 0x36, 0xd0, 0x9d, 0x42, 0x23, 0x04, 0x3a, 0x71, 0x05, 0xc5, 0x35, 0xb9, 0x22, 0x6b,
	0x64, 0x41, 0x47, 0x66, 0xdd, 0x2d, 0x23, 0x8f, 0x72, 0xac, 0x5b, 0xb5, 0x81, 0xee, 0xa8, 0x2d,
	0xd4, 0x85, 0xba, 0x94, 0xb8, 0x2e, 0xd7, 0x76, 0x02, 0x99, 0x00, 0x34, 0x0c, 0x66, 0xe2, 0x81,
	0x71, 0x92, 0xe0, 0x86, 0x1c, 0x29, 0x1d, 0xd4, 0x87, 0x93, 0x80, 0x91, 0x71, 0xc8, 0xa9, 0x2f,
	0x42, 0xb6, 0xc0, 0x4d, 0xe9, 0x38, 0xe8, 0x65, 0x7f, 0x11, 0x30, 0x46, 0x26, 0x8c, 0xe3, 0xd6,
	0xee, 0x2f, 0xf6, 0x12, 0xf5, 0xa0, 0xe1, 0xb9, 0x72, 0xd0, 0x96, 0x83, 0xbd, 0xea, 0x63, 0xe8,
	0x1d, 0x92, 0x70, 0x68, 0x12, 0xb3, 0x45, 0x42, 0x73, 0x48, 0xf7, 0x31, 0xf9, 0x87, 0x24, 0x21,
	0x29, 0x24, 0x0a, 0x48, 0x13, 0xc9, 0x68, 0x4c, 0xe7, 0xf4, 0x4f, 0x8c, 0xf6, 0x09, 0xca, 0x77,
	0xf2, 0x84, 0xd1, 0x5b, 0x15, 0x6a, 0xd3, 0x24, 0x40, 0x11, 0x74, 0xd4, 0xfb, 0x7a, 0x6e, 0xff,
	0x7c, 0xeb, 0xed, 0xc3, 0x13, 0x35, 0x46, 0xbf, 0xf7, 0xe6, 0xb1, 0x59, 0x9c, 0x7a, 0xf2, 0x65,
	0x71, 0x8a, 0xb7, 0x34, 0xee, 0x08, 0xc7, 0x2c, 0x4e, 0x85, 0x58, 0x16, 0xa7, 0x78, 0x4b, 0xe3,
	0x8e, 0x40, 0xbd, 0xba, 0x79, 0xdd, 0x98, 0xda, 0x7a, 0x63, 0x6a, 0x1f, 0x1b, 0x53, 0x7b, 0xd9,
	0x9a, 0x95, 0xf5, 0xd6, 0xac, 0xbc, 0x6f, 0xcd, 0xca, 0xe3, 0x45, 0x10, 0x8a, 0xd9, 0xd2, 0xb3,
	0x7d, 0x16, 0x0d, 0x8b, 0xb7, 0xa3, 0x28, 0x56, 0x5f, 0xa5, 0x48, 0x63, 0x9a, 0x78, 0x0d, 0xf9,
	0xa0, 0x5c, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x01, 0x46, 0x19, 0x97, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateLunar(ctx context.Context, in *MsgCreateLunar, opts ...grpc.CallOption) (*MsgCreateLunarResponse, error)
	UpdateLunar(ctx context.Context, in *MsgUpdateLunar, opts ...grpc.CallOption) (*MsgUpdateLunarResponse, error)
	DeleteLunar(ctx context.Context, in *MsgDeleteLunar, opts ...grpc.CallOption) (*MsgDeleteLunarResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateLunar(ctx context.Context, in *MsgCreateLunar, opts ...grpc.CallOption) (*MsgCreateLunarResponse, error) {
	out := new(MsgCreateLunarResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.zodiatic.Msg/CreateLunar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLunar(ctx context.Context, in *MsgUpdateLunar, opts ...grpc.CallOption) (*MsgUpdateLunarResponse, error) {
	out := new(MsgUpdateLunarResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.zodiatic.Msg/UpdateLunar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteLunar(ctx context.Context, in *MsgDeleteLunar, opts ...grpc.CallOption) (*MsgDeleteLunarResponse, error) {
	out := new(MsgDeleteLunarResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.zodiatic.Msg/DeleteLunar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateLunar(context.Context, *MsgCreateLunar) (*MsgCreateLunarResponse, error)
	UpdateLunar(context.Context, *MsgUpdateLunar) (*MsgUpdateLunarResponse, error)
	DeleteLunar(context.Context, *MsgDeleteLunar) (*MsgDeleteLunarResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateLunar(ctx context.Context, req *MsgCreateLunar) (*MsgCreateLunarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLunar not implemented")
}
func (*UnimplementedMsgServer) UpdateLunar(ctx context.Context, req *MsgUpdateLunar) (*MsgUpdateLunarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLunar not implemented")
}
func (*UnimplementedMsgServer) DeleteLunar(ctx context.Context, req *MsgDeleteLunar) (*MsgDeleteLunarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLunar not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateLunar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLunar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLunar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.zodiatic.Msg/CreateLunar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLunar(ctx, req.(*MsgCreateLunar))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLunar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLunar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLunar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.zodiatic.Msg/UpdateLunar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLunar(ctx, req.(*MsgUpdateLunar))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteLunar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteLunar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteLunar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.zodiatic.Msg/DeleteLunar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteLunar(ctx, req.(*MsgDeleteLunar))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zodiatic.zodiatic.zodiatic.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLunar",
			Handler:    _Msg_CreateLunar_Handler,
		},
		{
			MethodName: "UpdateLunar",
			Handler:    _Msg_UpdateLunar_Handler,
		},
		{
			MethodName: "DeleteLunar",
			Handler:    _Msg_DeleteLunar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zodiatic/tx.proto",
}

func (m *MsgCreateLunar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLunar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLunar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BadFor) > 0 {
		i -= len(m.BadFor)
		copy(dAtA[i:], m.BadFor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BadFor)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.GoodFor) > 0 {
		i -= len(m.GoodFor)
		copy(dAtA[i:], m.GoodFor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GoodFor)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.GodDirection) > 0 {
		i -= len(m.GodDirection)
		copy(dAtA[i:], m.GodDirection)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GodDirection)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.EightWords) > 0 {
		i -= len(m.EightWords)
		copy(dAtA[i:], m.EightWords)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EightWords)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Lunar) > 0 {
		i -= len(m.Lunar)
		copy(dAtA[i:], m.Lunar)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Lunar)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LunarNumber) > 0 {
		dAtA2 := make([]byte, len(m.LunarNumber)*10)
		var j1 int
		for _, num := range m.LunarNumber {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Yyyymmdd != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Yyyymmdd))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLunarResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLunarResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLunarResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLunar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLunar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLunar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BadFor) > 0 {
		i -= len(m.BadFor)
		copy(dAtA[i:], m.BadFor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BadFor)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.GoodFor) > 0 {
		i -= len(m.GoodFor)
		copy(dAtA[i:], m.GoodFor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GoodFor)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.GodDirection) > 0 {
		i -= len(m.GodDirection)
		copy(dAtA[i:], m.GodDirection)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GodDirection)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.EightWords) > 0 {
		i -= len(m.EightWords)
		copy(dAtA[i:], m.EightWords)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EightWords)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Lunar) > 0 {
		i -= len(m.Lunar)
		copy(dAtA[i:], m.Lunar)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Lunar)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LunarNumber) > 0 {
		dAtA4 := make([]byte, len(m.LunarNumber)*10)
		var j3 int
		for _, num := range m.LunarNumber {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintTx(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Yyyymmdd != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Yyyymmdd))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLunarResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLunarResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLunarResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLunar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLunar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLunar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Yyyymmdd != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Yyyymmdd))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLunarResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLunarResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLunarResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateLunar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Yyyymmdd != 0 {
		n += 1 + sovTx(uint64(m.Yyyymmdd))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.LunarNumber) > 0 {
		l = 0
		for _, e := range m.LunarNumber {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	l = len(m.Lunar)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EightWords)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GodDirection)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GoodFor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BadFor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLunarResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateLunar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Yyyymmdd != 0 {
		n += 1 + sovTx(uint64(m.Yyyymmdd))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.LunarNumber) > 0 {
		l = 0
		for _, e := range m.LunarNumber {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	l = len(m.Lunar)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EightWords)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GodDirection)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GoodFor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BadFor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateLunarResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteLunar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Yyyymmdd != 0 {
		n += 1 + sovTx(uint64(m.Yyyymmdd))
	}
	return n
}

func (m *MsgDeleteLunarResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateLunar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLunar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLunar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yyyymmdd", wireType)
			}
			m.Yyyymmdd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yyyymmdd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.LunarNumber = append(m.LunarNumber, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.LunarNumber) == 0 {
					m.LunarNumber = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.LunarNumber = append(m.LunarNumber, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field LunarNumber", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lunar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lunar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EightWords", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EightWords = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GodDirection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GodDirection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoodFor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoodFor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadFor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BadFor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLunarResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLunarResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLunarResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLunar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLunar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLunar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yyyymmdd", wireType)
			}
			m.Yyyymmdd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yyyymmdd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.LunarNumber = append(m.LunarNumber, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.LunarNumber) == 0 {
					m.LunarNumber = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.LunarNumber = append(m.LunarNumber, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field LunarNumber", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lunar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lunar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EightWords", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EightWords = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GodDirection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GodDirection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoodFor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoodFor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadFor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BadFor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLunarResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLunarResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLunarResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLunar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLunar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLunar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yyyymmdd", wireType)
			}
			m.Yyyymmdd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yyyymmdd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLunarResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLunarResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLunarResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
